channels:
  - conda-forge
dependencies:
  - arviz>=0.19.0
  - blackjax>=1.2.0
  - galsim>=2.3.0
  - h5py>=3.0.0
  - jupyter=1.0.*
  - mpi4py>=3
  - numpy>=1.18.0
    #- jax=0.4.27
    #- jaxlib=0.4.23
